stages:
  - build
  - test

image: node:20.15.0

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - rm -rf build
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public

pages:
  stage: test
  script:
    - ls
  artifacts:
    paths:
      - "public"
