# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x ,18.x , 20.x]

    steps:
      # checks code from repo
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup  node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: install dpendencies
        run: npm install

      - name: run build
        run: npm run build

      - name: run test
        run: npm test
